Update required activity
Infomaniak/android-core pull request #136
Opened 2024-02-16 09:25 UTC by FabianDevel

Depends on #135

2024-02-16 15:06 UTC, KevinBoulongne requested changes

2024-02-16 15:30 UTC, tevincent requested changes

2024-02-16 15:30 UTC, tevincent commented on Stores/src/standard/java/com/infomaniak/lib/stores/updatemanagers/InAppUpdateManager.kt
> +                }
```suggestion
                } else if (!viewModel.isUpdateBottomSheetShown) {
                    startUpdateFlow(appUpdateInfo)
                }
```

2024-02-19 07:52 UTC, tevincent approved these changes

2024-02-19 10:19 UTC, merged