Remove gif preview to use it only in the good project
Infomaniak/android-core pull request #197
Opened 2024-06-13 11:23 UTC by NicolasBourdin88

Wait for merge, i'm looking for other project that use gif preview

Depends on https://github.com/Infomaniak/android-kDrive/pull/1334

2024-06-14 12:28 UTC, KevinBoulongne approved these changes

2024-06-14 12:32 UTC, KevinBoulongne requested changes

2024-06-14 12:32 UTC, KevinBoulongne commented on src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
>                  customFactories.forEach { add(it) }
```suggestion
                customFactories.forEach(::add)
```

2024-06-19 07:46 UTC, tevincent approved these changes

2024-06-19 07:48 UTC, KevinBoulongne approved these changes

2024-06-19 08:16 UTC, merged