fix: Block app lock hacking
Infomaniak/android-core pull request #249
Opened 2024-12-19 10:07 UTC by LouisCAD

1. Use SystemClock.elapsedRealtime() instead of System.currentTimeMillis(),
 so it's not possible to unlock the app by setting the time in the past.
2. Ensure the app starts locked if the system had to kill the process.
3. Ensure all tasks get the lock when screen lock triggers app lock

2024-12-19 12:08 UTC, sirambd requested changes
Remove deprecated functions, and applies changes directly to kDrive and mail

2024-12-19 12:08 UTC, sirambd commented on AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
> +        private var isLocked = true
It's always true

2024-12-19 12:39 UTC, FabianDevel approved these changes

2024-12-26 11:40 UTC, sirambd approved these changes

2024-12-26 11:40 UTC, merged