Move update strings to Core
Infomaniak/android-core pull request #48
Opened 2023-03-28 06:41 UTC by FabianDevel

Move Update strings and google play extensions functions to Core

2023-03-28 08:49 UTC, KevinBoulongne requested changes

2023-03-28 08:49 UTC, KevinBoulongne commented on src/main/java/com/infomaniak/lib/core/utils/GplayExtensions.kt
> +    lifecycleScope.launch {
Specify the `launch` dispatchers.

2023-03-28 08:49 UTC, KevinBoulongne commented on src/main/java/com/infomaniak/lib/core/utils/GplayExtensions.kt
> +
```suggestion
```

2023-03-28 09:32 UTC, FabianDevel commented on src/main/java/com/infomaniak/lib/core/utils/GplayExtensions.kt
> +    lifecycleScope.launch {
We keep the default dispatcher for this

2023-03-28 09:36 UTC, KevinBoulongne approved these changes

2023-03-29 13:52 UTC, JorisBodin approved these changes

2023-03-29 13:52 UTC, merged